import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PageNavbar from "@/components/shared/nav/PageNavbar";
import AppProviders from "@/components/shared/providers/AppProviders";
import PageFooter from "@/components/shared/nav/PageFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>
          <PageNavbar />
          <div className="container mx-auto">{children}</div>
          <PageFooter />
        </AppProviders>
      </body>
    </html>
  );
}
